### ISSUE TITLE
[2.0.1] "Cannot create property 'prev' on boolean 'false'" (options.sourceMap) 

### ISSUE THREAD

**Issue by le0nik** [postcss/postcss-loader#207]
```
Module build failed: TypeError: Cannot create property 'prev' on boolean 'false'
    at Promise.resolve.then.then (../node_modules/postcss-loader/lib/index.js:125:47)
```

```
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: true,
        ...
      },
    },

```

These lines are the culprit:
https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L93
https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L125

postcss@1.3.3 works fine

webpack@2.5.1
OSX 10.12.4
Node.js 7.10.0
postcss-loader@2.0.0

**Comment by michael-ciniawsky** [comment]
Thats weird 😛 , you don't need to set `sourceMap: false`  no source map is the default, still needs to be fixed I wonder why this happens tbh

**Comment by polco** [comment]
i got the same error with the sourceMap set to 'true'  ;)

**Comment by michael-ciniawsky** [comment]
hmm.... 😛 on it

**Comment by le0nik** [comment]
@polco oh sorry my fault, this error appears when it's set to `true`, not `false`

**Comment by michael-ciniawsky** [comment]
@le0nik @polco Please post your config (`webpack.config.js`)  aswell just in case :)

**Comment by le0nik** [comment]
@michael-ciniawsky my config is huge and complex. Here's the styles loaders part:

```
    {
      loader: 'style-loader',
      options: {
        sourceMap: env.isDev,
      },
    }
    {
      loader: 'css-loader',
      options: {
        modules: true,
        importLoaders: 4,
        localIdentName: '[local]--[hash:base64:8]',
        minimize: {
          options: {
            safe: true,
            sourcemap: env.isDev,
          },
          // Otherwise it changes order of `z-index` which breaks our styles
          zindex: false,
        },
        sourceMap: env.isDev,
      },
    },
    {
      loader: 'resolve-url-loader',
      options: {
        sourceMap: env.isDev,
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: env.isDev,
        plugins: getPostcssPlugins,
      },
    },
    {
      loader: 'sass-loader',
      options: {
        sourceMap: env.isDev,
      },
    },
```

The error happened when `env.isDev` was set to `true`.

My `postcss.config.js` file is empty(i pass plugins through the `postcss-loader` options)

```
module.exports = {};
```

**Comment by polco** [comment]
webpack config:
```
webpackConfig.module.rules.push({
	test: /\.less$/,
	include: /src/,
	use: [
		{ loader: 'style-loader', options: { sourceMap: true } },
		{ loader: 'css-loader', options: { importLoaders: 2, root: config.get('ui-asset-url'),  sourceMap: true } },
		{ loader: 'postcss-loader', options: { sourceMap: true } },
		{ loader: 'less-loader', options: { sourceMap: true } }
	]
});
```

postcss.config.js
```
var cssnano = require('cssnano');

module.exports = {
	plugins: [
		cssnano({
			sourcemap: true,
			autoprefixer: {
				add: true,
				remove: true,
				browsers: ['last 2 versions']
			},
			safe: true,
			discardComments: {
				removeAll: true
			}
		})
	]
};
```

**Comment by le0nik** [comment]
Looks like the reason it happens is in this line https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L76

`loaderUtils.getOptions` always returns the same object in case of `options`(`query` gets parsed and a new object is returned every time) and when you delete `sourceMap` for one file it's always `undefined` after that.

**Comment by michael-ciniawsky** [comment]
Guys I can't reproduce the issue locally, but both of you use `sourcemap: true` in `cssnano`, could you both try without that? 🙃

**Comment by michael-ciniawsky** [comment]
@le0nik I see what you mean, mom I need another check for https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L79 to avoid the `delete options.x`

**Comment by polco** [comment]
tried it, still broken :/

**Comment by rejas** [comment]
This error happens too for me, here is my webpack.config-part: 
```
{
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [{
                        loader: 'css-loader',
                        options: {
                            minimize: true,
                            sourceMap: true
                        }
                    }, {
                        loader: 'postcss-loader',
                        options: {
                            plugins: function () {
                                return [
                                    require('autoprefixer')(config.autoprefixer),
                                    require('css-mqpacker')(),
                                    require('postcss-sprites')({
                                        spritePath: 'tmp/'
                                    })
                                ]
                            }
                        }
                    }, {
                        loader: 'less-loader',
                        options: {
                            sourceMap: true
                        }
                    }]
                })
            },
```

Error goes away, when I remove the two ```sourcemap```-options (don't aks why they were in there and not in post-css :-)

**Comment by michael-ciniawsky** [comment]
Yep confirmed it happens after the first file is processed by the laoder, I have a fix but a few minutes please 😛

**Comment by rejas** [comment]
No worries and hurry from my side, it's monday morning after all :-D

**Comment by polco** [comment]
yeah, it works with the previous version, so no rush :)

**Comment by frederikschubert** [comment]
I was working in parallel on this and did just see this issue as I wanted to make a PR. :)

**Comment by DanielRamosAcosta** [comment]
This is strange, I've set `sourceMap` to `'inline'`, but the error persists. I tried printing the value of `options` in [/index.js#L99](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L99) and the config is getting loaded for the first file, (with map set to `{ inline: true, annotation: false }`), but for the others is false...

**Comment by michael-ciniawsky** [comment]
Fixed in https://github.com/postcss/postcss-loader/commit/c4f006472a85d3bc36ae3f2f0e750291fd732b7b
Released in [v2.0.1](https://github.com/postcss/postcss-loader/releases/tag/v2.0.1)

**Comment by badtant** [comment]
I'm using 2.0.1 and still get the error

{
				test: /\.scss$/,
				use: [
					{
						loader: 'style-loader'
					},
					{
						loader: 'css-loader',
						options: {
							sourceMap: true
						}
					},
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: [autoprefixer]
                        }
                    },
					{
						loader: 'sass-loader',
						options: {
                            sourceMap: true,
							precision: 8
						}
					}
				]
			}

**Comment by brendanmoore** [comment]
Issue also persists for me with version 2.0.1. Is it worth reopening this issue?

**Comment by badtant** [comment]
I would say so

**Comment by michael-ciniawsky** [comment]
The check between `options.inWebpackConfig ? useConfig() : loadConfig()` is flanky I'm working on a solution (again 😛 ), but it is a nasty bug happening 'setup related'.

**Comment by michael-ciniawsky** [comment]
Please try the fix branch and provide feedback 😛 `npm i -D postcss/postcss-loader#fix`

**Comment by michael-ciniawsky** [comment]
[Hopefully 😛] fixed by https://github.com/postcss/postcss-loader/commit/e764761
Released in [`v2.0.2`](https://github.com/postcss/postcss-loader/releases/tag/v2.0.2)

Reopen if still regressions

**Comment by Meeeeow** [comment]
Said. Still got this error with `v2.0.2`:

Here is my loader configure:
```js
 {
        test: /\.less$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'postcss-loader'
          },
          {
            loader: 'less-loader',
            options: {
              sourceMap: true,
              modifyVars: theme
            }
          }
        ]
      }
```
```
ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader/lib!./~/less-loader/dist?{"sourceMap":true,"modifyVars":{"primary-color":"#00a5ff","link-color":"#00a5ff","font-size-base":"14px","@animation-duration-slow":".2s","@animation-duration-base":".1s","@animation-duration-fast":".05s"}}!./~/antd-mobile/lib/style/index.less
Module build failed: TypeError: Cannot create property 'prev' on boolean 'false'
    at Promise.resolve.then.then (D:\Corp\Project\node_modules\postcss-loader\lib\index.js:131:47)
 @ ./~/antd-mobile/lib/style/index.less 4:14-160 18:2-22:4 19:20-166
 @ ./~/antd-mobile/lib/style/index.web.js
 @ ./~/antd-mobile/lib/button/style/index.web.js
 @ ./src/modules/home/index.jsx
```

**Comment by michael-ciniawsky** [comment]
@Meeeeow Please try with `{ sourceMap: true }` in `postcss-loader` aswell, `postcss.config.js` still works with `sourceMap` option, otherwise the source map is discarded by `postcss-loader` anyways (without throwing an Error, i will check that again 😛 )

**Comment by Meeeeow** [comment]
@michael-ciniawsky Thanks, it works.

**Comment by gregorskii** [comment]
FYI I think this error occurs if the loader is set to pass sourceMaps:

```
use: [
            {
              loader: 'css-loader',
              options: {
                modules: true,
                minimize: true,
                importLoaders: 1,
                localIdentName: '[local]--[hash:base64:5]',
                sourceMap
              }
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap
              }
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap
              }
            }
          ]
```

And the postcss.config.js also includes the map property:

```
map: process.env.NODE_ENV === 'development' ? 'inline' : false
```

**Comment by michael-ciniawsky** [comment]
But `map` inside `postcss.config.js` isn't supported atm :), this is debateable, but I left it on purpose, because it doesn't fit into the way one enables sourcemaps 'normally'  with webpack (consistency).
Please use `{ sourceMap: true }` in `webpack.config.js`

**Comment by TrejGun** [comment]
@gregorskii removing of
```json
map: true
```
fixed my issue, thanks
