### ISSUE TITLE
[2.0.5] Output CSS Reversed/Jumbled

### ISSUE THREAD

**Issue by skipjack** [postcss/postcss-loader#210]
I'm seeing a weird issue with the output from this loader. I can't share the actual code/output but this is essentially what's happening:

__prior to loading__

``` css
.some-class {
  display: flex;
  flex-direction: column;
  color: black;

  &--mod {
    color: white;
  }
}
```

__after loading__

``` css
.some-class--mod {
  color: white;
}
.some-class {
  display: flex;
  flex-direction: column;
  color: black;
}
```

It's not all an exact reverse, but most of it is and the rest just seems randomly jumbled. Obviously this screws up the cascade (i.e. when `some-class` and `some-class--mod` are applied to the same element, the `color` is `black` instead of `white`). 

Here are the plugins I'm using _postcss-import_, _postcss-modular-scale_, _postcss-cssnext_, and _postcss-nested_.

**Comment by michael-ciniawsky** [comment]
`webpack.config.js`  && `postcss.config.js` please 😛

**Comment by skipjack** [comment]
That I can do 👍 

__webpack.config.js__ (excluding non css-related bits)

``` js
// Imports...

module.exports = (env = {}) => ({
    // ...

    module: {
        loaders: [
            // ...
            { 
                test: /\.css$/, 
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        'css-loader',
                        'postcss-loader' 
                    ]
                })
            }
        ]
    },

    plugins: [
        // ...
        new ExtractTextPlugin({
            filename: '[name].[contenthash].css',
            allChunks: true,
            disable: env.dev === true
        })
    ],

    // ...
})
```

__.postcssrc.js__

``` js
module.exports = {
    plugins: [
        require('postcss-import'),
        require('postcss-modular-scale'),
        require('postcss-cssnext'),
        require('postcss-nested')
    ]
}
```

**Comment by michael-ciniawsky** [comment]
As a heads up [postcss-nested v2.0.0 (6 hours ago)]https://github.com/postcss/postcss-nested/releases/tag/2.0.0 maybe related to the PostCSS v6.0.0 major bump in `postcss-loader`

[cssnext](https://github.com/MoOx/postcss-cssnext/blob/master/package.json#L49) ships with it's own nesting plugin included [`postcss-nesting`](https://github.com/jonathantneal/postcss-nesting), so maybe try with/without cssnext and put `postcss-nested` **before** cssnext in the plugin chain :)

**Comment by skipjack** [comment]
Thanks I'll try that.

**Comment by michael-ciniawsky** [comment]
https://github.com/postcss/postcss-nested/pull/52

Released in postcss-nested `v2.0.1`

**Comment by michael-ciniawsky** [comment]
Resolved 🙃 ? No rush but there is another bug which is to 💯  in `postcss-loader`, otherwise
please try the fix branch and provide feedback 😛 `npm i -D postcss/postcss-loader#fix`

**Comment by skipjack** [comment]
Haven't tested yet but let's close and, if anything, I'll re-open if the postcss-nested fix doesn't work.

**Comment by skipjack** [comment]
I tried that fix (upgraded both this loader as well as postcss-nested) and I'm still seeing the issue unfortunately. Digging around a bit to see if someone has opened a ticket for this in one one of the other plugins I'm using but it doesn't look like it.

> cssnext ships with it's own nesting plugin included postcss-nesting, so maybe try with/without cssnext and put postcss-nested before cssnext in the plugin chain :)

Yeah, however we are using the `&__element` and `&--modifier` rules to follow BEM which require also adding `postcss-nested`. I did try messing with the order of plugins which didn't seem to have an effect.

My gut feeling is that it must be either this package or `postcss-nested` that's causing this issue. I'll open an issue over there as well.

**Comment by skipjack** [comment]
Also tried blowing away all `node_modules` and re-installing from scratch with no luck. I'll keep testing and see if I can nail it down to one thing.

**Comment by evilebottnawi** [comment]
@skipjack try to `npm cache clear` and remove node_modules and again `npm i`

**Comment by skipjack** [comment]
Ok I'm pretty sure it is this package that's causing the issue. It happens when I upgrade just loader.

**Comment by evilebottnawi** [comment]
@skipjack can your create minimal test repo? Seems it is related to `postcss` plugin. I don't see any logic in `loader` related to this problem.

**Comment by skipjack** [comment]
Yeah I can do that.

**Comment by skipjack** [comment]
As promised: [postcss-issue-demo](https://github.com/skipjack/postcss-loader-issue)

**Comment by skipjack** [comment]
I'm happy to close this issue and move it elsewhere once we determine the root cause of the problem.

**Comment by michael-ciniawsky** [comment]
@skipjack 

### PostCSS Issue Demo

**package.json** (The most likely case) 
```diff
-  "postcss-nested": "^1.0.0",
+ "postcss-nested": "^2.x",
```

The most likely case ☝️  😛  since `postcss-nested =< v1.0.0` is incompatible with `postcss-loader >= v2.0.0` bc of a PostCSS 6 . I can confirm this, it broke my stuff aswell 🙃 

**.postcssrc.js**
```diff
module.exports = {
    plugins: [
        require('postcss-import'),
        require('postcss-modular-scale'),
+      require('postcss-nested') // Maybe you don't need it, 
        require('postcss-cssnext'), // because I include postcss-nesting :),
-       require('postcss-nested') // but postcss-nested [SASS] !== postcss-nesting [CSSWG Spec]
    ]
}
```

You need to test that, if it worked before all good ¯\_(ツ)_/¯, but it could be related to `postcss-nesting` aswell , which may also has eventual incompabilities with PostCSS 6 API atm.

**Comment by skipjack** [comment]
@michael-ciniawsky 

Unfortunately that doesn't fix it, I had tried that locally as well. See [this commit](https://github.com/skipjack/postcss-loader-issue/commit/61f942ee0a7da2cf9a088c019967fe0574f2ec66) I just pushed in the demo repo.

**Comment by ai** [comment]
Nope. I will look in next few hours.

**Comment by michael-ciniawsky** [comment]
![loaderissue](https://cloud.githubusercontent.com/assets/5419992/26007563/54794946-3741-11e7-8d14-f525f531f210.png)


Its cssnext @see https://github.com/MoOx/postcss-cssnext/issues/374

**Comment by skipjack** [comment]
Awesome, thanks for all of your help! Sorry I didn't pick up on this earlier.

**Comment by michael-ciniawsky** [comment]
It worked with `cssnext` in this small example as you can see in the screenshot, but it doesn't really use any other `cssnext` features besides nesting so be really ⚠️ using it :D

**Comment by skipjack** [comment]
Yeah, I subscribed to that cssnext issue and will wait to upgrade everything until that's complete.
